/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { KeywordService } from "../keyword.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { KeywordCreateInput } from "./KeywordCreateInput";
import { Keyword } from "./Keyword";
import { Request } from "../../request/base/Request";
import { KeywordFindManyArgs } from "./KeywordFindManyArgs";
import { KeywordWhereUniqueInput } from "./KeywordWhereUniqueInput";
import { KeywordUpdateInput } from "./KeywordUpdateInput";
import { RequestFindManyArgs } from "../../request/base/RequestFindManyArgs";
import { RequestWhereUniqueInput } from "../../request/base/RequestWhereUniqueInput";
import { TrendAnalysisFindManyArgs } from "../../trendAnalysis/base/TrendAnalysisFindManyArgs";
import { TrendAnalysis } from "../../trendAnalysis/base/TrendAnalysis";
import { TrendAnalysisWhereUniqueInput } from "../../trendAnalysis/base/TrendAnalysisWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class KeywordControllerBase {
  constructor(
    protected readonly service: KeywordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Keyword })
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createKeyword(
    @common.Body() data: KeywordCreateInput
  ): Promise<Keyword> {
    return await this.service.createKeyword({
      data: data,
      select: {
        createdAt: true,
        id: true,
        keyword: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Keyword] })
  @ApiNestedQuery(KeywordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keywords(@common.Req() request: Request): Promise<Keyword[]> {
    const args = plainToClass(KeywordFindManyArgs, request.query);
    return this.service.keywords({
      ...args,
      select: {
        createdAt: true,
        id: true,
        keyword: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Keyword })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keyword(
    @common.Param() params: KeywordWhereUniqueInput
  ): Promise<Keyword | null> {
    const result = await this.service.keyword({
      where: params,
      select: {
        createdAt: true,
        id: true,
        keyword: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Keyword })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateKeyword(
    @common.Param() params: KeywordWhereUniqueInput,
    @common.Body() data: KeywordUpdateInput
  ): Promise<Keyword | null> {
    try {
      return await this.service.updateKeyword({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          keyword: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Keyword })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteKeyword(
    @common.Param() params: KeywordWhereUniqueInput
  ): Promise<Keyword | null> {
    try {
      return await this.service.deleteKeyword({
        where: params,
        select: {
          createdAt: true,
          id: true,
          keyword: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/requests")
  @ApiNestedQuery(RequestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Request",
    action: "read",
    possession: "any",
  })
  async findRequests(
    @common.Req() request: Request,
    @common.Param() params: KeywordWhereUniqueInput
  ): Promise<Request[]> {
    const query = plainToClass(RequestFindManyArgs, request.query);
    const results = await this.service.findRequests(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        keyword: {
          select: {
            id: true,
          },
        },

        requestedAt: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/requests")
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  async connectRequests(
    @common.Param() params: KeywordWhereUniqueInput,
    @common.Body() body: RequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requests: {
        connect: body,
      },
    };
    await this.service.updateKeyword({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/requests")
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  async updateRequests(
    @common.Param() params: KeywordWhereUniqueInput,
    @common.Body() body: RequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requests: {
        set: body,
      },
    };
    await this.service.updateKeyword({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/requests")
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  async disconnectRequests(
    @common.Param() params: KeywordWhereUniqueInput,
    @common.Body() body: RequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requests: {
        disconnect: body,
      },
    };
    await this.service.updateKeyword({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/trendAnalyses")
  @ApiNestedQuery(TrendAnalysisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "read",
    possession: "any",
  })
  async findTrendAnalyses(
    @common.Req() request: Request,
    @common.Param() params: KeywordWhereUniqueInput
  ): Promise<TrendAnalysis[]> {
    const query = plainToClass(TrendAnalysisFindManyArgs, request.query);
    const results = await this.service.findTrendAnalyses(params.id, {
      ...query,
      select: {
        analyzedAt: true,
        createdAt: true,
        id: true,

        keyword: {
          select: {
            id: true,
          },
        },

        trendData: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trendAnalyses")
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  async connectTrendAnalyses(
    @common.Param() params: KeywordWhereUniqueInput,
    @common.Body() body: TrendAnalysisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trendAnalyses: {
        connect: body,
      },
    };
    await this.service.updateKeyword({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trendAnalyses")
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  async updateTrendAnalyses(
    @common.Param() params: KeywordWhereUniqueInput,
    @common.Body() body: TrendAnalysisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trendAnalyses: {
        set: body,
      },
    };
    await this.service.updateKeyword({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trendAnalyses")
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  async disconnectTrendAnalyses(
    @common.Param() params: KeywordWhereUniqueInput,
    @common.Body() body: TrendAnalysisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trendAnalyses: {
        disconnect: body,
      },
    };
    await this.service.updateKeyword({
      where: params,
      data,
      select: { id: true },
    });
  }
}
