/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Request } from "./Request";
import { RequestCountArgs } from "./RequestCountArgs";
import { RequestFindManyArgs } from "./RequestFindManyArgs";
import { RequestFindUniqueArgs } from "./RequestFindUniqueArgs";
import { CreateRequestArgs } from "./CreateRequestArgs";
import { UpdateRequestArgs } from "./UpdateRequestArgs";
import { DeleteRequestArgs } from "./DeleteRequestArgs";
import { SearchResultFindManyArgs } from "../../searchResult/base/SearchResultFindManyArgs";
import { SearchResult } from "../../searchResult/base/SearchResult";
import { Keyword } from "../../keyword/base/Keyword";
import { RequestService } from "../request.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Request)
export class RequestResolverBase {
  constructor(
    protected readonly service: RequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Request",
    action: "read",
    possession: "any",
  })
  async _requestsMeta(
    @graphql.Args() args: RequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Request])
  @nestAccessControl.UseRoles({
    resource: "Request",
    action: "read",
    possession: "any",
  })
  async requests(
    @graphql.Args() args: RequestFindManyArgs
  ): Promise<Request[]> {
    return this.service.requests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Request, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Request",
    action: "read",
    possession: "own",
  })
  async request(
    @graphql.Args() args: RequestFindUniqueArgs
  ): Promise<Request | null> {
    const result = await this.service.request(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Request)
  @nestAccessControl.UseRoles({
    resource: "Request",
    action: "create",
    possession: "any",
  })
  async createRequest(
    @graphql.Args() args: CreateRequestArgs
  ): Promise<Request> {
    return await this.service.createRequest({
      ...args,
      data: {
        ...args.data,

        keyword: args.data.keyword
          ? {
              connect: args.data.keyword,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Request)
  @nestAccessControl.UseRoles({
    resource: "Request",
    action: "update",
    possession: "any",
  })
  async updateRequest(
    @graphql.Args() args: UpdateRequestArgs
  ): Promise<Request | null> {
    try {
      return await this.service.updateRequest({
        ...args,
        data: {
          ...args.data,

          keyword: args.data.keyword
            ? {
                connect: args.data.keyword,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Request)
  @nestAccessControl.UseRoles({
    resource: "Request",
    action: "delete",
    possession: "any",
  })
  async deleteRequest(
    @graphql.Args() args: DeleteRequestArgs
  ): Promise<Request | null> {
    try {
      return await this.service.deleteRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SearchResult], { name: "searchResults" })
  @nestAccessControl.UseRoles({
    resource: "SearchResult",
    action: "read",
    possession: "any",
  })
  async findSearchResults(
    @graphql.Parent() parent: Request,
    @graphql.Args() args: SearchResultFindManyArgs
  ): Promise<SearchResult[]> {
    const results = await this.service.findSearchResults(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Keyword, {
    nullable: true,
    name: "keyword",
  })
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "read",
    possession: "any",
  })
  async getKeyword(@graphql.Parent() parent: Request): Promise<Keyword | null> {
    const result = await this.service.getKeyword(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
