/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TrendAnalysisService } from "../trendAnalysis.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TrendAnalysisCreateInput } from "./TrendAnalysisCreateInput";
import { TrendAnalysis } from "./TrendAnalysis";
import { Request } from "../../request/base/Request";
import { TrendAnalysisFindManyArgs } from "./TrendAnalysisFindManyArgs";
import { TrendAnalysisWhereUniqueInput } from "./TrendAnalysisWhereUniqueInput";
import { TrendAnalysisUpdateInput } from "./TrendAnalysisUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TrendAnalysisControllerBase {
  constructor(
    protected readonly service: TrendAnalysisService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TrendAnalysis })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTrendAnalysis(
    @common.Body() data: TrendAnalysisCreateInput
  ): Promise<TrendAnalysis> {
    return await this.service.createTrendAnalysis({
      data: {
        ...data,

        keyword: data.keyword
          ? {
              connect: data.keyword,
            }
          : undefined,
      },
      select: {
        analyzedAt: true,
        createdAt: true,
        id: true,

        keyword: {
          select: {
            id: true,
          },
        },

        trendData: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TrendAnalysis] })
  @ApiNestedQuery(TrendAnalysisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trendAnalyses(
    @common.Req() request: Request
  ): Promise<TrendAnalysis[]> {
    const args = plainToClass(TrendAnalysisFindManyArgs, request.query);
    return this.service.trendAnalyses({
      ...args,
      select: {
        analyzedAt: true,
        createdAt: true,
        id: true,

        keyword: {
          select: {
            id: true,
          },
        },

        trendData: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TrendAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trendAnalysis(
    @common.Param() params: TrendAnalysisWhereUniqueInput
  ): Promise<TrendAnalysis | null> {
    const result = await this.service.trendAnalysis({
      where: params,
      select: {
        analyzedAt: true,
        createdAt: true,
        id: true,

        keyword: {
          select: {
            id: true,
          },
        },

        trendData: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TrendAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTrendAnalysis(
    @common.Param() params: TrendAnalysisWhereUniqueInput,
    @common.Body() data: TrendAnalysisUpdateInput
  ): Promise<TrendAnalysis | null> {
    try {
      return await this.service.updateTrendAnalysis({
        where: params,
        data: {
          ...data,

          keyword: data.keyword
            ? {
                connect: data.keyword,
              }
            : undefined,
        },
        select: {
          analyzedAt: true,
          createdAt: true,
          id: true,

          keyword: {
            select: {
              id: true,
            },
          },

          trendData: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TrendAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTrendAnalysis(
    @common.Param() params: TrendAnalysisWhereUniqueInput
  ): Promise<TrendAnalysis | null> {
    try {
      return await this.service.deleteTrendAnalysis({
        where: params,
        select: {
          analyzedAt: true,
          createdAt: true,
          id: true,

          keyword: {
            select: {
              id: true,
            },
          },

          trendData: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
